### ISSUE TITLE
UI musts are a no-no

### ISSUE THREAD

**Issue by annevk** [InternetExplorer/directory-upload#16]
Don't require UI. Especially not when it's only focused towards output on a screen. We might not have buttons forever either.

**Comment by annevk** [comment]
(I don't think making these "should" is really an improvement by the way.)

**Comment by aliams** [comment]
The reasons we are defining UI are twofold:
1. We want to allow OSes to be able to support a combined file and directory picker in the future and  not require the web developer to make changes. The two-button UI makes it possible for OSes that don't support the scenario to be able to choose a directory or files.
2. If you don't specify the UI, you lose the context and need for the chooseDirectory method.

We have been debating whether or not this is actually the best way to solve this problem going forward mainly because, like you said, we'd be requiring UI. Having said that, if you have a more elegant way of solving this problem, we are open to suggestions =)

**Comment by annevk** [comment]
Basically what you have now is a non-starter since it's not applicable to all implementations of HTML. You can suggest UI, you cannot require it. You can definitely not require something as specific as "two buttons".

**Comment by aliams** [comment]
If we make the UI a suggestion, do we also make the `HTMLInputElement.chooseDirectory` method a suggestion? What would be the best practice here?

**Comment by annevk** [comment]
Well that is about capabilities. That is different from requiring specific UI.

**Comment by arunranga** [comment]
We no longer require UI. Closing this.
