### ISSUE TITLE
FileSystem API and this draft conflict

### ISSUE THREAD

**Issue by annevk** [InternetExplorer/directory-upload#19]
While it's already super confusing that `Directory` is seemingly defined here but also elsewhere, the referenced draft does not define a `path` member.

**Comment by inexorabletash** [comment]
Yeah; mentally, I'm thinking of these specs as building on each other:

[File API](https://w3c.github.io/FileAPI/) - Files, Blobs, file upload, reading (i.e. what's live now)
[Directory Upload](https://wicg.github.io/directory-upload/proposal.html) - adds Directories, directory upload
[File System](http://w3c.github.io/filesystem-api) - adds roots, URLs, writing

... but they were not written in that order so the dependencies don't quite work. Moz is possibly furthest along implementing here - does it make sense to refactor the specs to align with the implementation order, since it seems like at least some browsers will deploying incrementally?

**Comment by annevk** [comment]
I don't really know how far along Mozilla is really... I believe the FileSystem specification is not being worked on at the moment.

**Comment by aliams** [comment]
I agree with @inexorabletash with how they should be building on top of each other. Mozilla already has an implementation of the directory upload proposal in nightly builds. As for the FileSystem API, I expect that it will take some time before it is actually ready for implementation. That was one of the reasons that we extracted the `Directory` interface and put it in the directory upload proposal (so we don't have to wait for the FileSystem API to be fully spec'd out before we can solve the directory upload  scenario). This will make it so that when the FileSystem API is ready to be implemented, vendors will already have the `Directory` interface from the directory upload spec and can simply extend it.

**Comment by annevk** [comment]
@aliams you're not actually addressing any of the concerns raised with that comment.

**Comment by arunranga** [comment]
@annevk : is the use of the 'partial' keyword to extend Directory wrong in the WICG spec, e.g. adding properties is not allowed? 

I agree that we should be consistent. The canonical Directory should have a path.

**Comment by aliams** [comment]
I wonder if it even makes sense to have Directory.path? Please see comments in #10.

**Comment by annevk** [comment]
@arunranga it's wrong because it duplicates stuff. Also, it's wrong if the layering as per @inexorabletash's comment is the other way around.

**Comment by arunranga** [comment]
I agree with @inexorabletash, and think the "order" of specs might be as follows:
1. File API for File and Blob, etc.
2. Directory Upload for Directory
3. Changes to HTML initially proposed in 2. above (HTMLInputElement, Drag and Drop, Form Submission).
4. FileSystem API

So 4. above would actually extend 2.
Latest PR should address this issue by removing dependencies on FileSystem API.

**Comment by annevk** [comment]
Thank you @arunranga. Haven't reviewed the latest draft yet but I think that would address this issue. You might want to drop links to the commits here to make it easier for folks to review.

**Comment by arunranga** [comment]
In fact, https://wicg.github.io/directory-upload/proposal.html reflects the updated draft. Happy to close this after holding it open for a review period (other changes may land as well).
