### ISSUE TITLE
Easier way to get files without complicated asynchronous traversal code

### ISSUE THREAD

**Issue by marcoscaceres** [InternetExplorer/directory-upload#26]
It seems like the 90% use case for this is going to be to just get all the files from a directory (as one can't do much with a directory anyway), so why don't we provide a nice method to just get a flattened list of files? 

``` JS
directory.getFiles({recursive: true}) //or {deep: true}, so to avoid complicated traversal 
  .then(filterImagesUnder2MB)
  .then(images => Promise.all(files.map(uploadImage))
  .then(showDone)
  .catch(err => console.error("Uploading failed!", err))
```

As files contain their own stats info, a developer can get at the path directly from the file to see where they are in the directory hierarchy. 

WDYT?

**Comment by arunranga** [comment]
@marcoscaceres :
That seems like sugar that a library could add. I'm not against sugar -- I'm arguing for something slightly sugary in WICG/directory-upload#10 -- but this seems heavier than a property.

Note that we went the iteration route because "smarter" primitives haven't been added to ES, like AsyncIterator (or Observable). When that happens, methods like enumerate() and enumerateDeep() would have provided the best blend of sugar and API. That's w3c/filesystem-api#4

**Comment by marcoscaceres** [comment]
> That seems like sugar that a library could add.

I think we learned from IDB that that is not a great idea (i.e., we should not defer to libraries to most common cases).

Additionally, if you look at how much async bouncing needs to be done waiting for all the generated promises to settle (given lots of directories, including in the example in the spec), it seems like it could be more performant to just let the underlying implementation gather all the files and associated metadata. 

> Note that we went the iteration route because "smarter" primitives haven't been added to ES, like AsyncIterator (or Observable). When that happens, methods like enumerate() and enumerateDeep() would have provided the best blend of sugar and API.

I see. I'd still think we should target current ES6 feature set tho, with, as you say, an eye to the future where developers might be able to prollyfill to support the async iterators (e.g., through implementing the appropriate behavior through a JS provided symbol or whatever).

**Comment by arunranga** [comment]
@marcoscaceres : I'm sold, and I'll put in a change that resembles your proposal.

But a few things: you said that Files contain enough stat information to deduce path. That's not strictly true, actually: http://www.w3.org/TR/FileAPI/#dfn-file

File objects expose a name property, but not a path property -- name is spec'd to explicitly NOT include path information. I think they _should_ and in fact I'd like to modify WICG/directory-upload#10 so that both File objects and Directory objects expose a path property, in addition to a name property.

**Comment by aliams** [comment]
Earlier on we ran some tests to verify the performance impact of processing very large directories with many files and sub-directories. It turns out that there is better perceived performance when providing files and sub-directories at 1 level deep rather than waiting for the entire directory structure to be processed all at once since developers would be able to provide more timely feedback to the user. The added benefit is that you can kick off the uploads for the files that you have already retrieved as you continue to receive more files. Originally, we wanted to take advantage of `AsyncIterators` as mentioned by @arunranga, but we opted for Promises with the compromise that we would need to allow for more incremental feedback to the developer. Having said that, I believe that we should continue to not have a way to retrieve a flattened file list until we have a more robust primitive such as `AsyncIterator` to allow for better user experiences.

**Comment by jwatt** [comment]
> It seems like the 90% use case for this is going to be to just get all the files from a directory (as one can't do much with a directory anyway), so why don't we provide a nice method to just get a flattened list of files?

We could do that, but we'd still want to involve at least one Promise to get the flat list as you have in your code. (Since there's no way for the site to know how large the directory tree a user might drop/pick will be, or how slow it might be to create the flattened list.)

I think I side with @aliams on not providing this due to the reasons he gave above, but if we did provide it maybe we could have getFileTree() and getPotentiallySlowFlatFileTree(). Making the name inconvenient and the risks explicit in the name would discourage usage.

**Comment by jwatt** [comment]
The getFiles() method added in 9082102ee33f094eae2df7d5c1a9ff9dbe92bb3e resolved this I think.
